

package termostatoVista;

import javax.swing.ButtonGroup;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import javax.swing.JToggleButton;
import termostatoControlador.TermostatoControlador;
import termostatoModelo.TermostatoModelo;

/**
 *Clase para manejar todo lo relacionado con los cambios visuales en la inerfaz
 * 
 * @author juatorr
 * @author hectori
 */
public class TermostatoVista extends javax.swing.JFrame {

    private TermostatoControlador miControlador;
    private TermostatoModelo miModelo;
    
    
    public TermostatoVista() {
        initComponents();
        miModelo = new TermostatoModelo(this, miControlador);
        miControlador = new TermostatoControlador(this, miModelo);
        miControlador.initComponents();

    }

    public JToggleButton getInicioButton(){
        return InicioButton;
    }
    public JPanel getModoManual() {
        return ModoManual;
    }

    public JPanel getModoEditar() {
        return ModoEditar;
    }

    public void setModoEditar(JPanel ModoEditar) {
        this.ModoEditar = ModoEditar;
    }
    
    public JToggleButton getManualButton(){
        return ManualButton;
    }
    
    public JToggleButton getAutoButton(){
        return AutoButton;
    }
    
    public JToggleButton getEditButton(){
        return EditButton;
    }
    
    public JToggleButton getdocetresButton(){
        return doceTresButton;
    }
    
    public JToggleButton getcuatroSieteButton(){
        return cuatroSieteButton;
    }

    public JToggleButton getochoOnceButton() {
        return ochoOnceButton;
    }
    
    public JToggleButton getdoceQuinceButton(){
        return doceQuinceButton;
    }
    
    public JToggleButton getdiciseisDiecinueveButton(){
        return dieciseisDiecinueveButton;
    }
    
    public JToggleButton getveinteVeintresButton(){
        return veinteVeintresButton;
    }
    
    public JComboBox getprogramaCombobox(){
        return ProgramaComboBox;
    }
    
    public JTextField getHora(){
        return Hora;
    }
    
    public JTextField getTemperatura(){
        return Temperartura;
    }
    
    public JLabel getA(){
        return ALabel;
    }

    public JLabel getDomingo() {
        return Domingo;
    }

    public JLabel getLunes() {
        return Lunes;
    }

    public JLabel getMartes() {
        return Martes;
    }

    public JLabel getMiercoles() {
        return Miercoles;
    }

    public JLabel getJueves() {
        return Jueves;
    }

    public JLabel getViernes() {
        return Viernes;
    }

    public JLabel getSabado() {
        return Sabado;
    }

    public JComboBox<String> getProgramaComboBox() {
        return ProgramaComboBox;
    }

    public ButtonGroup getButtonGroup1() {
        return buttonGroup1;
    }

    public JSpinner getMinima() {
        return Minima;
    }

    public void setMinima(JSpinner Minima) {
        this.Minima = Minima;
    }

    public JSpinner getMaxima() {
        return Maxima;
    }

    public void setMaxima(JSpinner Maxima) {
        this.Maxima = Maxima;
    }

    public JSpinner getHorasSpinner() {
        return HorasSpinner;
    }

    public void setHorasSpinner(JSpinner HorasSpinner) {
        this.HorasSpinner = HorasSpinner;
    }

    public JLabel getTemporizador() {
        return Temporizador;
    }
    
    
    

   
    
    
    
    
    
    
    
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Fondo = new javax.swing.JPanel();
        Días = new javax.swing.JPanel();
        Lunes = new javax.swing.JLabel();
        Martes = new javax.swing.JLabel();
        Miercoles = new javax.swing.JLabel();
        Jueves = new javax.swing.JLabel();
        Viernes = new javax.swing.JLabel();
        Sabado = new javax.swing.JLabel();
        Domingo = new javax.swing.JLabel();
        Intermedio = new javax.swing.JPanel();
        Botonera_Centro = new javax.swing.JPanel();
        ZPrograma = new javax.swing.JPanel();
        ProgramaActLabel = new javax.swing.JLabel();
        ALabel = new javax.swing.JLabel();
        Temporizador = new javax.swing.JLabel();
        ProgramaComboBox = new javax.swing.JComboBox<>();
        Zintervalos = new javax.swing.JPanel();
        doceTresButton = new javax.swing.JToggleButton();
        cuatroSieteButton = new javax.swing.JToggleButton();
        ochoOnceButton = new javax.swing.JToggleButton();
        doceQuinceButton = new javax.swing.JToggleButton();
        dieciseisDiecinueveButton = new javax.swing.JToggleButton();
        veinteVeintresButton = new javax.swing.JToggleButton();
        ModoEditar = new javax.swing.JPanel();
        MinimaLabel = new javax.swing.JLabel();
        Minima = new javax.swing.JSpinner();
        MaximaLabel = new javax.swing.JLabel();
        Maxima = new javax.swing.JSpinner();
        HorayTemp = new javax.swing.JPanel();
        Hora = new javax.swing.JTextField();
        Temperartura = new javax.swing.JTextField();
        BotonesAbajo = new javax.swing.JPanel();
        InicioButton = new javax.swing.JToggleButton();
        ManualButton = new javax.swing.JToggleButton();
        AutoButton = new javax.swing.JToggleButton();
        EditButton = new javax.swing.JToggleButton();
        ModoManual = new javax.swing.JPanel();
        HorasLabel = new javax.swing.JLabel();
        HorasSpinner = new javax.swing.JSpinner();
        IniciarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        Lunes.setText("Lunes");
        Días.add(Lunes);

        Martes.setText("Martes");
        Días.add(Martes);

        Miercoles.setText("Miércoles");
        Días.add(Miercoles);

        Jueves.setText("Jueves");
        Días.add(Jueves);

        Viernes.setText("Viernes");
        Días.add(Viernes);

        Sabado.setText("Sábado");
        Días.add(Sabado);

        Domingo.setText("Domingo");
        Días.add(Domingo);

        Botonera_Centro.setLayout(new java.awt.GridLayout(3, 1));

        ZPrograma.setLayout(new java.awt.GridLayout(1, 0, 168, 0));

        ProgramaActLabel.setText("Programa actual:");
        ZPrograma.add(ProgramaActLabel);

        ALabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ALabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/termostatoVista/iconfinder_letter_A_red_1553029.png"))); // NOI18N
        ALabel.setText(" ");
        ZPrograma.add(ALabel);

        Temporizador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/termostatoVista/clock_hour_minute_second_time_timer_watch_icon_123193.png"))); // NOI18N
        Temporizador.setToolTipText("");
        ZPrograma.add(Temporizador);

        ProgramaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Programa 0", "Programa 1", "Programa 2" }));
        ProgramaComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProgramaComboBoxActionPerformed(evt);
            }
        });
        ZPrograma.add(ProgramaComboBox);

        Botonera_Centro.add(ZPrograma);

        doceTresButton.setText("0-3");
        doceTresButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doceTresButtonActionPerformed(evt);
            }
        });
        Zintervalos.add(doceTresButton);

        cuatroSieteButton.setText("4-7");
        cuatroSieteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuatroSieteButtonActionPerformed(evt);
            }
        });
        Zintervalos.add(cuatroSieteButton);

        ochoOnceButton.setText("8-11");
        ochoOnceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ochoOnceButtonActionPerformed(evt);
            }
        });
        Zintervalos.add(ochoOnceButton);

        doceQuinceButton.setText("12-15");
        doceQuinceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doceQuinceButtonActionPerformed(evt);
            }
        });
        Zintervalos.add(doceQuinceButton);

        dieciseisDiecinueveButton.setText("16-19");
        dieciseisDiecinueveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dieciseisDiecinueveButtonActionPerformed(evt);
            }
        });
        Zintervalos.add(dieciseisDiecinueveButton);

        veinteVeintresButton.setText("20-23");
        veinteVeintresButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veinteVeintresButtonActionPerformed(evt);
            }
        });
        Zintervalos.add(veinteVeintresButton);

        Botonera_Centro.add(Zintervalos);

        MinimaLabel.setText("Mínima");
        ModoEditar.add(MinimaLabel);

        Minima.setModel(new javax.swing.SpinnerNumberModel(0, 0, 40, 1));
        Minima.setEditor(new javax.swing.JSpinner.NumberEditor(Minima, ""));
        Minima.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                MinimaStateChanged(evt);
            }
        });
        ModoEditar.add(Minima);

        MaximaLabel.setText("Máxima");
        ModoEditar.add(MaximaLabel);

        Maxima.setModel(new javax.swing.SpinnerNumberModel(0, 0, 40, 1));
        Maxima.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                MaximaStateChanged(evt);
            }
        });
        ModoEditar.add(Maxima);

        Botonera_Centro.add(ModoEditar);

        HorayTemp.setLayout(new java.awt.GridLayout(1, 2));

        Hora.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        Hora.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Hora.setText("00:00:00 h");
        HorayTemp.add(Hora);

        Temperartura.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        Temperartura.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Temperartura.setText("19ºC");
        HorayTemp.add(Temperartura);

        InicioButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/termostatoVista/iconfinder_power-button_353434 (1).png"))); // NOI18N
        InicioButton.setText("Inicio");
        InicioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InicioButtonActionPerformed(evt);
            }
        });
        BotonesAbajo.add(InicioButton);

        buttonGroup1.add(ManualButton);
        ManualButton.setText("Manual");
        ManualButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManualButtonActionPerformed(evt);
            }
        });
        BotonesAbajo.add(ManualButton);

        buttonGroup1.add(AutoButton);
        AutoButton.setText("Automatico");
        AutoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AutoButtonActionPerformed(evt);
            }
        });
        BotonesAbajo.add(AutoButton);

        buttonGroup1.add(EditButton);
        EditButton.setText("Editar");
        EditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditButtonActionPerformed(evt);
            }
        });
        BotonesAbajo.add(EditButton);

        HorasLabel.setText("Horas:");
        ModoManual.add(HorasLabel);

        HorasSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        HorasSpinner.setToolTipText("");
        ModoManual.add(HorasSpinner);

        IniciarButton.setText("Iniciar");
        IniciarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarButtonActionPerformed(evt);
            }
        });
        ModoManual.add(IniciarButton);

        javax.swing.GroupLayout IntermedioLayout = new javax.swing.GroupLayout(Intermedio);
        Intermedio.setLayout(IntermedioLayout);
        IntermedioLayout.setHorizontalGroup(
            IntermedioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HorayTemp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Botonera_Centro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BotonesAbajo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(IntermedioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ModoManual, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE))
        );
        IntermedioLayout.setVerticalGroup(
            IntermedioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IntermedioLayout.createSequentialGroup()
                .addComponent(HorayTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Botonera_Centro, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonesAbajo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, Short.MAX_VALUE))
            .addGroup(IntermedioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IntermedioLayout.createSequentialGroup()
                    .addContainerGap(122, Short.MAX_VALUE)
                    .addComponent(ModoManual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(40, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout FondoLayout = new javax.swing.GroupLayout(Fondo);
        Fondo.setLayout(FondoLayout);
        FondoLayout.setHorizontalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Días, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Intermedio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        FondoLayout.setVerticalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addComponent(Días, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Intermedio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(Fondo);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cuatroSieteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuatroSieteButtonActionPerformed
        miControlador.setBoton(1);
    }//GEN-LAST:event_cuatroSieteButtonActionPerformed

    private void ManualButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManualButtonActionPerformed
        miControlador.manualButton(true);
    }//GEN-LAST:event_ManualButtonActionPerformed

    private void IniciarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarButtonActionPerformed
        miControlador.iniciarManual();
    }//GEN-LAST:event_IniciarButtonActionPerformed

    private void AutoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AutoButtonActionPerformed
        miControlador.autoButton(false);
    }//GEN-LAST:event_AutoButtonActionPerformed

    private void EditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButtonActionPerformed
        miControlador.editarButton(true);
    }//GEN-LAST:event_EditButtonActionPerformed

    private void InicioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InicioButtonActionPerformed
        miControlador.inicioButton();
    }//GEN-LAST:event_InicioButtonActionPerformed

    private void ProgramaComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProgramaComboBoxActionPerformed
        miControlador.SelProg();
    }//GEN-LAST:event_ProgramaComboBoxActionPerformed

    private void doceTresButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doceTresButtonActionPerformed
        miControlador.setBoton(0);
    }//GEN-LAST:event_doceTresButtonActionPerformed

    private void ochoOnceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ochoOnceButtonActionPerformed
        miControlador.setBoton(2);
    }//GEN-LAST:event_ochoOnceButtonActionPerformed

    private void doceQuinceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doceQuinceButtonActionPerformed
        miControlador.setBoton(3);
    }//GEN-LAST:event_doceQuinceButtonActionPerformed

    private void dieciseisDiecinueveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dieciseisDiecinueveButtonActionPerformed
        miControlador.setBoton(4);
    }//GEN-LAST:event_dieciseisDiecinueveButtonActionPerformed

    private void veinteVeintresButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veinteVeintresButtonActionPerformed
        miControlador.setBoton(5);
    }//GEN-LAST:event_veinteVeintresButtonActionPerformed

    private void MinimaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_MinimaStateChanged
        miControlador.setMinima();
    }//GEN-LAST:event_MinimaStateChanged

    private void MaximaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_MaximaStateChanged
        miControlador.setMaxima();
    }//GEN-LAST:event_MaximaStateChanged


    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ALabel;
    private javax.swing.JToggleButton AutoButton;
    private javax.swing.JPanel Botonera_Centro;
    private javax.swing.JPanel BotonesAbajo;
    private javax.swing.JLabel Domingo;
    private javax.swing.JPanel Días;
    private javax.swing.JToggleButton EditButton;
    private javax.swing.JPanel Fondo;
    private javax.swing.JTextField Hora;
    private javax.swing.JLabel HorasLabel;
    private javax.swing.JSpinner HorasSpinner;
    private javax.swing.JPanel HorayTemp;
    private javax.swing.JButton IniciarButton;
    private javax.swing.JToggleButton InicioButton;
    private javax.swing.JPanel Intermedio;
    private javax.swing.JLabel Jueves;
    private javax.swing.JLabel Lunes;
    private javax.swing.JToggleButton ManualButton;
    private javax.swing.JLabel Martes;
    private javax.swing.JSpinner Maxima;
    private javax.swing.JLabel MaximaLabel;
    private javax.swing.JLabel Miercoles;
    private javax.swing.JSpinner Minima;
    private javax.swing.JLabel MinimaLabel;
    private javax.swing.JPanel ModoEditar;
    private javax.swing.JPanel ModoManual;
    private javax.swing.JLabel ProgramaActLabel;
    private javax.swing.JComboBox<String> ProgramaComboBox;
    private javax.swing.JLabel Sabado;
    private javax.swing.JTextField Temperartura;
    private javax.swing.JLabel Temporizador;
    private javax.swing.JLabel Viernes;
    private javax.swing.JPanel ZPrograma;
    private javax.swing.JPanel Zintervalos;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JToggleButton cuatroSieteButton;
    private javax.swing.JToggleButton dieciseisDiecinueveButton;
    private javax.swing.JToggleButton doceQuinceButton;
    private javax.swing.JToggleButton doceTresButton;
    private javax.swing.JToggleButton ochoOnceButton;
    private javax.swing.JToggleButton veinteVeintresButton;
    // End of variables declaration//GEN-END:variables

    

}
